import Head from "next/head";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import React, { useState } from "react";
import { Flex, Box, Heading, useToast, Input, Stack, IconButton } from "@chakra-ui/react";
import Characters from "../Components/Characters";
import { SearchIcon, CloseIcon } from "@chakra-ui/icons";

export default function Home(results) {
  const initialState = results;
  const [characters, setCharacters] = useState(initialState.characters);
  const [search, setSearch] = useState("");
  const toast = useToast();

  return (
    <Flex direction="column" justify="center" align="center">
      <Head>
        <title>Nextjs & Graphql</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box mb={4} flexDirection="column" align="center" justify="center" py={8}>
        <Heading as="h4" size="xl" mb={8}>
          Rick & Morty
        </Heading>
        <form
          onSubmit={async e => {
            e.preventDefault();
            const results = await fetch("/api/APiRick", {
              method: "POST",
              body: search
            });
            const { characters, error } = await results.json();
            if (error) {
              toast({
                position: "bottom",
                title: "An Error",
                description: error,
                status: "error",
                duration: 5000,
                isClosable: true
              });
            } else {
              setCharacters(characters);
            }
          }}
        >
          <Stack maxWidth="350px" width="100%" isInline mb={8}>
            <Input
              placeholder="Search Chara"
              value={search}
              border="none"
              onChange={e => setSearch(e.target.value)}
            />
            <IconButton
              variant="outline"
              colorScheme="blue"
              arial-label="Search Database"
              icon={<SearchIcon />}
              disabled={search === ""}
              type="submit"
            />
            <IconButton
              variant="outline"
              colorScheme="red"
              arial-label="Reset Database"
              icon={<CloseIcon />}
              disabled={search === ""}
              onClick={async () => {
                setSearch("");
                setCharacters(initialState.characters);
              }}
            />
          </Stack>
        </form>
        <Characters characters={characters} />
      </Box>
    </Flex>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql",
    cache: new InMemoryCache()
  });
  const { data } = await client.query({
    query: gql`
      query {
        characters(page: 1) {
          info {
            count
            pages
          }
          results {
            name
            id
            location {
              id
              name
            }
            origin {
              id
              name
            }
            episode {
              id
              episode
              air_date
            }
            image
          }
        }
      }
    `
  });
  return {
    props: {
      characters: data.characters.results
    }
  };
}
